---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/dag-andersen/k8s-ucp-app-gitops

